### PR TITLE
Do UPnP port forwarding if possible

### PR DESCRIPTION
**Pull request by ziggythehamster**
This requires you to `apt-get install python-miniupnpc` ([p.d.o link](https://packages.debian.org/jessie/python-miniupnpc)) but otherwise requires no further OS configuration.

### CODE REVIEW

**Comment by Kazade** [comment]
Amazing! I tried this once before but my router wouldn't work with it so I didn't release it untested.

I'll merge and try to get a new DreamPi release out in the next few weeks.

**Comment by ziggythehamster** [comment]
:D. I've got a few other changes coming. I just want to make sure they're adequately tested before I send them over here. I also don't have a Pi to test with (this is all in a VM), so you'll want to make sure that I didn't break anything before you cut a new release.

**Comment by Kazade** [comment]
Hi!

So I've tested this, and everything sort of works... (except my router hates it and just complains with Invalid Action for most of the ports).

The problem is it takes *ages* to set up the forwarding - over a minute on my set up. I moved the setup/teardown so we only do it on boot/shutdown, but that didn't really help much it just meant I was waiting ages for the DreamPi to start up.

Does Starlancer really require all of those ports? (I'm hoping not!)

I've disabled this for now until we can figure out a way to do it without holding up the dreampi itself (another thread maybe?)

**Comment by ziggythehamster** [comment]
I actually noticed this myself but haven't had time to work on a PR due to my move. Go ahead and revert this PR, I won't be offended :). I want to move this to a separate boot service for all the reasons you mentioned. I should be unpacked enough in the next week or so to refine this.

**Comment by Kazade** [comment]
I'll have a go at forking it out into a thread on boot, I think that'll solve everything to be honest :)

**Comment by Blayer98** [comment]
Hi, is this still being worked on? I literally can’t play over half of the Dreamcast’s online games that support online gameplay because my router will not allow port forwarding with ip addresses, and I cannot get another router and connect the two.

If this isn’t being worked on, can there at least be some instructions on setting this up for my DreamPi? Thanks.

**Comment by ziggythehamster** [comment]
What router do you have? UPnP support would require that your router allow you to enable insecure port forwards - the Dreamcast is bridged, and the DreamPi software is what does the forwarding, so you end up in an impossible situation if you can't enable insecure forwards. If you can't forward by IP, then I'd assume you also can't disable UPnP secure forwards. Maybe you can.

I need to sync my branch to latest DreamPi and get it working in VBox again.

**Comment by Blayer98** [comment]
TalkTalk HG633 Super Router. Unfortunately, it’s not me who pays for it so I can’t replace it myself...

I’m able to set UPnP as enabled/disabled, I think that’s it though.

**Pull request merged**
